name: Release

on:
  release:
    types: [released]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  release:
    name: "Build and Release (${{ matrix.target.displayName }}, ${{ matrix.target.rustTarget }}, ${{ matrix.target.runner }})"
    timeout-minutes: 10
    permissions:
      contents: write
    strategy:
      matrix:
        target:
          # Windows (cross-compiled from Linux, build-only)
          - { displayName: 32-bit Windows,
              rustTarget: i686-pc-windows-gnu,
              runner: 'ubuntu-latest',
              canTest: false }

          - { displayName: 64-bit Windows,
              rustTarget: x86_64-pc-windows-gnu,
              runner: 'ubuntu-latest',
              canTest: false }

          # Linux
          - { displayName: 32-bit Linux,
              rustTarget: i686-unknown-linux-gnu,
              runner: 'ubuntu-latest',
              canTest: true }

          - { displayName: 64-bit Linux,
              rustTarget: x86_64-unknown-linux-gnu,
              runner: 'ubuntu-latest',
              canTest: true }

          - { displayName: ARM32 ARMv6 Linux,
              rustTarget: arm-unknown-linux-gnueabi,
              runner: 'ubuntu-latest',
              canTest: false }

          - { displayName: ARM32 ARMv7 Linux,
              rustTarget: armv7-unknown-linux-gnueabihf,
              runner: 'ubuntu-latest',
              canTest: false }

          - { displayName: ARM64 Linux,
              rustTarget: aarch64-unknown-linux-gnu,
              runner: 'ubuntu-latest',
              canTest: false }

          # macOS
          - { displayName: 64-bit macOS,
              rustTarget: x86_64-apple-darwin,
              runner: 'macos-latest',
              canTest: true }

          - { displayName: ARM64 macOS,
              rustTarget: aarch64-apple-darwin,
              runner: 'macos-latest',
              canTest: true }

    runs-on: ${{ matrix.target.runner }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 1

      - name: Update apt-get package list
        if: ${{ contains(matrix.target.runner, 'ubuntu') }}
        run: sudo apt-get update

      - name: Add Rust Target
        run: rustup target add ${{ matrix.target.rustTarget }}

      - name: Add Windows Build Dependencies
        if: ${{ contains(matrix.target.rustTarget, 'pc-windows') }}
        run: sudo apt-get install -y gcc-mingw-w64 nasm

      - name: Add ARM32 Build Dependencies
        if: ${{ contains(matrix.target.rustTarget, 'arm') }}
        run: sudo apt-get install -y gcc-arm-linux-gnueabihf gcc-arm-linux-gnueabi gcc-arm-none-eabi binutils-arm-linux-gnueabi

      - name: Add ARM64 Build Dependencies
        if: ${{ contains(matrix.target.rustTarget, 'aarch64') && contains(matrix.target.runner, 'ubuntu') }}
        run: sudo apt-get install -y gcc-aarch64-linux-gnu crossbuild-essential-arm64

      - name: Add 32-bit Linux Build Dependencies
        if: ${{ contains(matrix.target.rustTarget, 'i686-unknown-linux-gnu') }}
        run: sudo apt-get install -y gcc-multilib

      - name: Run Tests
        if: ${{ matrix.target.canTest }}
        run: cargo test --release --target ${{ matrix.target.rustTarget }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target.rustTarget }}

      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        with:
          name: githubrepocloner-${{ matrix.target.rustTarget }}${{ endsWith(matrix.target.rustTarget, '-windows-gnu') && '.exe' || '' }}
          path: ./target/${{ matrix.target.rustTarget }}/release/githubrepocloner${{ endsWith(matrix.target.rustTarget, '-windows-gnu') && '.exe' || '' }}

      - name: Upload Release Asset
        env:
          GH_TOKEN: ${{ github.token }}
        run:
          cp ./target/${{ matrix.target.rustTarget }}/release/githubrepocloner${{ endsWith(matrix.target.rustTarget, '-windows-gnu') && '.exe' || '' }} ./githubrepocloner-${{ github.ref_name }}-${{ matrix.target.rustTarget }}${{ endsWith(matrix.target.rustTarget, '-windows-gnu') && '.exe' || '' }} &&
          gh release upload ${{ github.event.release.tag_name }} ./githubrepocloner-${{ github.ref_name }}-${{ matrix.target.rustTarget }}${{ endsWith(matrix.target.rustTarget, '-windows-gnu') && '.exe' || '' }}#"githubrepocloner-${{ github.ref_name }}-${{ matrix.target.rustTarget }}${{ endsWith(matrix.target.rustTarget, '-windows-gnu') && '.exe' || '' }} (${{ matrix.target.displayName }})"
